### ISSUE TITLE
Game refuses to launch with BLT installed as of Update 21 Beta

### ISSUE THREAD

**Issue by ILC-YTP** [Luffyyy/Raid-BLT#3]
When IPHLPAPI.dll is placed in the root folder of RAID WWII, the game will not start. On Steam, the game will show that it is running for a few seconds before it switches back to the play button. Nothing pops up when running the game. Payday 2's BLT, for comparison, installs and works just fine

This update also mentioned that all mod_overrides mods should now be put into the "mods" folder. I wonder if this means the _mod_overrides_ and _mods_  folder will be merged and work as one proper mod folder, or if they just moved the _mod_overrides_ folder to _mods_, forcing all BLT mods to make a new home. Can't test that out though if BLT isn't working in the first place.

**Comment by LegitGreenBoi** [comment]
This is still an issue with the final release of Update 21

**Comment by BangL** [comment]
this is fixed by https://github.com/Luffyyy/Raid-BLT/commit/4f7a0b1ee4006e68c77242d9f7b193e58927d534
